### ISSUE TITLE
No metadata message for {publisherID}:{dataSetWriterId} received yet!

### ISSUE THREAD

**Issue by simonsikkeland** [digitaltwinconsortium/UA-CloudTwin#4]
Hi, 
We are working on a Twin for a factory with OPC UA devices, the data is flowing through a VM with IoT Edge and a OPC UA publisher to the IoT-Hub->UA-CloudTwin->ADT.  We are getting the following information when we are running UA-CloudTwin:
"No metadata message for {publisherID}:{dataSetWriterId} received yet!" and the digital twins does not contain the metadata necessary to create relations and hierarchy.

The publisher looks like this with but with more nodes, different names and IP as well. 
\
`
  {
    "EndpointUrl": "opc.tcp://111.111.11.111",
    "DataSetWriterGroup": "rh",
    "DataSetWriterId": 3,
    "OpcNodes": [
      {
        "Id": "ns=1;s=/codesys/volatile/pdp/Multivac/R530/Advance",
        "HeartbeatIntervalTimespan": "00:01:00",
        "OpcSamplingInterval": 2000,
        "OpcPublishingInterval": 5000,
        "DataSetFieldId": "R530-Advance",
        "DisplayName": "R530-Advance"
      }
  }
`
\
In azure the message looks something like this:
\
`
[
  {
    "MessageId": "4690",
    "MessageType": "ua-data",
    "PublisherId": "opc.tcp://111.111.11.111:rh",
    "DataSetWriterGroup": "rh",
    "Messages": [
      {
        "DataSetWriterId": "3",
        "SequenceNumber": 4690,
        "MetaDataVersion": {
          "MajorVersion": 1,
          "MinorVersion": 0
        },
        "Timestamp": "2022-11-29T06:20:26.2187Z",
        "Payload": {
          "R530-Advance": {
            "Value": false,
            "SourceTimestamp": "2022-11-29T06:14:32.09145Z",
            "ServerTimestamp": "2022-11-29T06:14:32.3252Z"
          }
        }
      }
    ]
  }
]
`

Would it be possible to provide a valid example of a payload containing message data and metadata necessary to create a small hierarchy?
For example a factory with two machines with two sensors.

**Comment by barnstee** [comment]
OPC Publisher does not yet support OPC UA metadata messages. There is a feature request pending here: https://github.com/Azure/Industrial-IoT/issues/1680. UA Cloud Publisher already supports metadata messages and can be accessed here: https://github.com/barnstee/UA-CloudPublisher. Alternatively, you can switch off parsing metadata messages via the IGNORE_MISSING_METADATA environment variable, but the digital twin instances will be named "opc.tcp://111.111.11.111:rh" and "3" in your sample case...
