### ISSUE TITLE
Telemetry does not load, but Dtl models are imported automatically.

### ISSUE THREAD

**Issue by Pardaloka** [digitaltwinconsortium/UA-CloudTwin#6]
I am using Prosys Simulation Opcua as per the attached images with telemetry, but I cannot receive any data. The messages arrive in IoT Hub and Event Hub, I tried to use the ignore metadata tags. Below are images with logs and my settings. I would really like to use this tool, if you can help me I would be extremely grateful.!

![20240830_092658.jpg](https://github.com/user-attachments/assets/148faa0b-1356-495f-93b5-207a9bd0f4fb)

![20240830_092628.jpg](https://github.com/user-attachments/assets/2be6a485-b4b2-4aa4-9fea-e91483c172e7)

![20240830_092913.jpg](https://github.com/user-attachments/assets/089868d1-b6dd-4fd4-8efe-69545bc6ea0a)

**Comment by barnstee** [comment]
Before spending a lot of time debugging, what's your use case for using ADT instead of sending the data directly to Azure Data Explorer (ADX)? Our reference architecture no longer relies on ADT as ADX now has graph support and covers the ADT functionality we used to use ADT for.

**Comment by Pardaloka** [comment]
![data-history-architecture](https://github.com/user-attachments/assets/289596b3-ac3d-4481-b6e7-9ecbd66c9d5f)

Erich, thank you very much for your attention, I was imagining the OPCUA data leaving the IoT hub going to the ADT so that I could relate it and then record it in the ADX. In short, the cloud twin does this ingestion between IoTHUB and ADT. 

After ingesting ADX, I will understand how this integration with ADT works I'm not aware really.

**Comment by barnstee** [comment]
Yes, this is out of date, the new ref architecture looks like this: https://learn.microsoft.com/en-us/azure/iot/tutorial-iot-industrial-solution-architecture#reference-solution-architecture
